namespace GatewayStub.Api.Enums
{
    public enum EMethodId : byte
    {
        AuthLogin = 1,
        AuthSendRequestToResetPassword = 2,
        AuthResetPassword = 3,
        AuthConfirmPassword = 4,
        AuthCreateRequestToConfirmEmail = 5,
        AuthConfirmEmailByCode = 6,
        AuthDeleteEmailRequest = 7,
        AuthSetPassword = 8,
        AuthResentConfirmationMail = 9,
        AuthLogout = 10,
        AuthEmptyMethod = 11,
        AuthAssignProviderAccountToDeviceId = 12,
        GameBalancerStopSearching = 13,
        GameBalancerGameStartedNotification = 14,
        HeroesGetHeroesListByUserId = 15,
        HeroesHeroAddedNotification = 16,
        InventoryAddedItemNotification = 17,
        InventoryGetItemsList = 18,
        LobbyStartGame = 19,
        GetRegions = 21,
        RegionsSet = 22,
        UserGetSettings = 23,
        UserSetSettings = 24,
        StatsEquipItem = 25,
        StatsEquipHero = 26,
        StatsUnequipItem = 27,
        UserGetUserData = 28,
        UserUpdateUsername = 29,
        UserGetLeaderBoard = 30,
        UserUpdateProfileImage = 31,
        ItemsGetListOfAvailable = 32,
        CodesUse = 33,
        BalanceUserBalanceChangedNotification = 34,
        ProductPurchase = 35,
        ProductGetHeroList = 36,
        ProductGetEquipmentList = 37,
        WalletGetByUserId = 38,
        BalanceGetBalanceByUserId = 39,
        BalanceGetBalancesByUserIdAsArray = 41,
        BalanceGetListWithPagination = 42,
        Checkin = 127,
    }
}